export const FETCH_RENTALS_INIT = "FETCH_RENTALS_INIT";
export const FETCH_RENTALS_SUCCESS = "FETCH_RENTALS_SUCCESS";
export const FETCH_RENTALS_FAIL = "FETCH_RENTALS_FAIL";
export const FETCH_RENTAL_BY_ID_INIT = "FETCH_RENTAL_BY_ID_INIT";
export const FETCH_RENTAL_BY_ID_SUCCESS = "FETCH_RENTAL_BY_ID_SUCCESS";
export const FETCH_RENTAL_BY_ID_FAIL = "FETCH_RENTAL_BY_ID_FAIL";
export const UPDATE_RENTAL_INIT = "UPDATE_RENTAL_INIT";
export const UPDATE_RENTAL_SUCCESS = "UPDATE_RENTAL_SUCCESS";
export const UPDATE_RENTAL_FAIL = "UPDATE_RENTAL_FAIL";

export const FETCH_USER_BOOKINGS_INIT = "FETCH_USER_BOOKINGS_INIT";
export const FETCH_USER_BOOKINGS_SUCCESS = "FETCH_USER_BOOKINGS_SUCCESS";
export const FETCH_USER_BOOKINGS_FAIL = "FETCH_USER_BOOKINGS_FAIL";
export const UPDATE_BOOKINGS = "UPDATE_BOOKINGS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
